name: delivery

on: [pull_request]

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run Delivery
      uses: actions/checkout@master
      env:
        CHEF_LICENSE: accept-no-persist
