---
name: delivery

on: [pull_request]

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Check out code
        uses: Xorima/test-action@master
      - name: Run Chef Delivery
        uses: actionshub/chef-delivery@master
        env:
          CHEF_LICENSE: accept-no-persist
