name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: show env vars
      run: printenv
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run delivery
      run: | 
        curl -L https://omnitruck.chef.io/install.sh |
        sudo bash -s -- -c stable -P chefdk
        chef exec delivery local all
